# Form implementation generated from reading ui file 'wind.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_map = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_map.setText("")
        self.label_map.setObjectName("label_map")
        self.gridLayout.addWidget(self.label_map, 2, 0, 1, 1)
        self.radioButton_dark = QtWidgets.QRadioButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_dark.setFont(font)
        self.radioButton_dark.setObjectName("radioButton_dark")
        self.gridLayout.addWidget(self.radioButton_dark, 0, 0, 1, 1)
        self.radioButton_light = QtWidgets.QRadioButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_light.setFont(font)
        self.radioButton_light.setChecked(True)
        self.radioButton_light.setObjectName("radioButton_light")
        self.gridLayout.addWidget(self.radioButton_light, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_dark.setText(_translate("MainWindow", "Темная"))
        self.radioButton_light.setText(_translate("MainWindow", "Светлая"))
